In [8]:
import numpy as np

This command will import numpy package into the local symbol table with a dummy name 'np'

In [9]:
L=[1,2,3,4,5] # intializing a list

In [10]:
np.array(L)

array([1, 2, 3, 4, 5])

In [11]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

array() is one of the most important methods that is being used for contructing arrays. It can convert a list or a tuple into a valid usable array. A set will be converted into array but it will not construct a usable array with customized datatype. This can be illustrated in the following lines.

In [12]:
T=1,2,3,4 # tuple

In [13]:
A=np.array(T) # converting tuple into array

In [14]:
A

array([1, 2, 3, 4])

In [15]:
S={1,2,3,4} # set 

In [16]:
B=np.array(S) # converting set into an array

In [17]:
B

array({1, 2, 3, 4}, dtype=object)

Here we can see that datatype of the invidual elements of the set is integer but dtype of the array is taken as 'object' by the interpreter. ( It implies that the whole set is taken as a single element of the array)

In [18]:
print(type(B)) # to check the type of the variable B

<class 'numpy.ndarray'>


The function constructed a valid 'n dimensional' (nd) array

In [19]:
A.dtype # method dtype helps to identify the datatype of array elements

dtype('int32')

'int32' indicates the datatype of each array element is integer and it occupies 4 bytes of memory location

In [20]:
B.dtype

dtype('O')

Here dtype is 'O' means individual elements of the set can't be accessed 

In [21]:
L=[1,2,3,[4,5,6],7,8,9]

In [22]:
A=np.array(L)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part.

To convert a list or tuple into a valid array, they shall be homogeneous in nature. In the above example, L is a nested list with one of its member is another list. numpy function 'array' can't convert this list into a valid array. Either all elements shall be integers or all elements shall be lists

In [23]:
L=[[1,2,3],[4,5,6]] # all elements are lists

In [24]:
A=np.array(L)

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6]])

There are many built in methods that helps to analyze various features of an array. Some basic methods are
 1. dtype- to identify the datatype of the array elements.
 dtype is also a keyword argument of array function that helps to customize the datatype of   array elements.

 For example , A.dtype will return the datatype of array elements if A is an array
 But np.array(L, dtype='f4') will construct an array where each element is of single precisionfloating point format

2. ndim - to identify the number of dimensions of the array
3. size - to identify the total number of elements present in an array
4. shape - In the case of a 2D array, this method returns the rows and columns


In [26]:
A.dtype

dtype('int32')

In [27]:
A.ndim # to check the number of dimensions, n=1 means a row array or column array, n=2 implies two dimensional array (eqvt to matrix)


2

In [28]:
A.size

6

In [29]:
B=np.array(L, dtype='f') # assigning floating point datatype

In [30]:
B

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

'f' by deafult assigns single precision
'f2' gives 16 bit floating point data
'f4' single precision
'f8' double precision

In [31]:
C=np.array(L,dtype='u4') # unsigned integer datatype

In [32]:
C

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

In [33]:
D=np.array(L,dtype='u')

TypeError: data type 'u' not understood

In [34]:
D=np.array(L,dtype='u2')

In [35]:
D

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint16)

In [36]:
E=np.array(L,dtype='complex')

In [37]:
E

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [38]:
E.dtype

dtype('complex128')

by default, interpreter assigns 128 bits ( 16 bytes) for complex data (64 bit for real part and 64 bits for imaginery part). 

In [39]:
F=np.array(L,dtype='c8') # trying to assign 8 bytes for complex datatype

In [40]:
F

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [66]:
F1=np.array(L,dtype='c16') # another  way to assign 16 byte complex data

In [67]:
F2=np.array(L,dtype='c4')

TypeError: data type 'c4' not understood

Complex datatype shall be of either 64 bits or 128 bits. All other formats are invalid

In [41]:
G=np.array(L,dtype='c') 

In [42]:
G 

array([[b'1', b'2', b'3'],
       [b'4', b'5', b'6']], dtype='|S1')

It is evident that 'c' does not act as short form of complex but it is taken as ' character' by the interpreter.  

All elements are converted into byte strings. datatype is 'byte String' where each string has only one character (hence S1).

In [43]:
L='Made in India'.split()

In [44]:
L

['Made', 'in', 'India']

In [45]:
H=np.array(L,dtype='c')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [46]:
I=np.array(L)

In [47]:
I

array(['Made', 'in', 'India'], dtype='<U5')

NOTE: 1. integer elements can be converted into byte strings but strings of unequal length 
         can't be converted into byte string format.
      2. A list of strings by default will be  converted into an array of unicode character 
         strings by python interpreter. 
      3. Here '<' indicates  'little endian byte addressing' U indicates 'Unicode' and '5' 
         indicates maximum length of any array element

In [48]:
J=np.array(L,dtype='S') # 'S' indicates byte strings of unequal length 

In [49]:
J

array([b'Made', b'in', b'India'], dtype='|S5')

In [50]:
K=np.array(L,dtype='i')

ValueError: invalid literal for int() with base 10: 'Made'

In [51]:
M=np.array(L,dtype=bool)

In [52]:
M

array([ True,  True,  True])

In [53]:
M.ndim

1

In [54]:
M.dtype

dtype('bool')

In [55]:
L=[1,2,3,4]

In [57]:
MM=np.array(L,dtype='?')

In [58]:
MM

array([ True,  True,  True,  True])

In [59]:
A.shape

(2, 3)

In [60]:
B.shape

(2, 3)

In [61]:
M.shape

(3,)

In [62]:
MM.shape

(4,)

In [68]:
N=np.asarray(L)

In [69]:
N

array([1, 2, 3, 4])

In [70]:
N.dtype

dtype('int32')

In [71]:
N.ndim

1

In [72]:
N.shape

(4,)

Similar to array () function, there is  a function 'asarray() in numpy. It will also construct array from the given list, tuple. But if the input is already an array, asarray will generate a pointer to the existing array ( shallow copy). np.array() will always construct a new array object (deep copy)

In [73]:
P=np.asarray(N)

In [74]:
P

array([1, 2, 3, 4])

In [75]:
P is N

True

In [76]:
P==N

array([ True,  True,  True,  True])

In [77]:
Q=np.array(N)

In [78]:
Q

array([1, 2, 3, 4])

In [79]:
Q is N # 'is' operator checks whether both object names point to the same memory location

False

In [80]:
Q==N # '==' function checks element by element identity

array([ True,  True,  True,  True])